import type { ShellUiGateway } from "../application/shellUiGateway";
import { appLocaleRepository } from "./appLocaleRepository";
import {
  readExplorerOpenPreference,
  readGitPanelPinnedPreference,
  readSidebarPinnedPreference,
  writeExplorerOpenPreference,
  writeGitPanelPinnedPreference,
  writeSidebarPinnedPreference,
} from "./shellPreferencesStorage";
import { shellRuntime } from "./shellRuntime";
import {
  closeNativeWindow,
  destroyNativeWindow,
  getAppVersion,
  hideNativeWindow,
  isNativeWindowFullscreen,
  isTauriRuntime,
  listenWindowFileDrops,
  minimizeNativeWindow,
  openExternalUrl,
  saveTextFile,
  selectDirectoryPath,
  selectFilePaths,
  selectTextFile,
  setNativeWindowFullscreen,
  startNativeWindowDrag,
  startNativeWindowResizeDrag,
  toggleNativeWindowMaximize,
} from "./nativeShellCapabilities";

export const shellUiGateway: ShellUiGateway = {
  closeNativeWindow,
  destroyNativeWindow,
  getAppVersion,
  getPersistedAppLocale: appLocaleRepository.getPersistedLocale,
  hideNativeWindow,
  isNativeWindowFullscreen,
  isTauriRuntime,
  listenWindowFileDrops,
  minimizeNativeWindow,
  now: shellRuntime.now,
  openExternalUrl,
  readExplorerOpenPreference,
  readGitPanelPinnedPreference,
  readSidebarPinnedPreference,
  saveTextFile,
  selectDirectoryPath,
  selectFilePaths,
  selectTextFile,
  setNativeWindowFullscreen,
  setPersistedAppLocale: appLocaleRepository.setPersistedLocale,
  startNativeWindowDrag,
  startNativeWindowResizeDrag,
  toggleNativeWindowMaximize,
  writeExplorerOpenPreference,
  writeGitPanelPinnedPreference,
  writeSidebarPinnedPreference,
};
