import { ipc } from "../../../lib/ipc";
import type { WorkspaceGateway } from "../application/workspaceGateway";
import {
  readLastRepoByWorkspace,
  readLastWorkspaceId,
  rememberLastRepo,
  writeLastWorkspaceId,
} from "./workspacePreferencesStorage";

export const workspaceRepository = {
  archiveWorkspace: ipc.archiveWorkspace,
  bindCueLightProject: ipc.bindCueLightProject,
  clearWorkspaceStartupPreset: ipc.clearWorkspaceStartupPreset,
  getCueLightBinding: ipc.getCueLightBinding,
  getRepos: ipc.getRepos,
  getWorkspaceStartupPreset: ipc.getWorkspaceStartupPreset,
  hasWorkspaceGitSelection: ipc.hasWorkspaceGitSelection,
  listArchivedWorkspaces: ipc.listArchivedWorkspaces,
  listWorkspaces: ipc.listWorkspaces,
  normalizeWorkspaceStartupPreset: ipc.normalizeWorkspaceStartupPreset,
  normalizeWorkspaceStartupPresetRaw: ipc.normalizeWorkspaceStartupPresetRaw,
  openWorkspace: ipc.openWorkspace,
  revealWorkspacePath: ipc.revealPath,
  restoreWorkspace: ipc.restoreWorkspace,
  serializeWorkspaceStartupPreset: ipc.serializeWorkspaceStartupPreset,
  setRepoGitActive: ipc.setRepoGitActive,
  setRepoTrustLevel: ipc.setRepoTrustLevel,
  setWorkspaceStartupPreset: ipc.setWorkspaceStartupPreset,
  setWorkspaceStartupPresetRaw: ipc.setWorkspaceStartupPresetRaw,
  setWorkspaceGitActiveRepos: ipc.setWorkspaceGitActiveRepos,
  unbindCueLightProject: ipc.unbindCueLightProject,
};

export const workspaceGateway: WorkspaceGateway = {
  archiveWorkspace: workspaceRepository.archiveWorkspace,
  bindCueLightProject: workspaceRepository.bindCueLightProject,
  clearWorkspaceStartupPreset: workspaceRepository.clearWorkspaceStartupPreset,
  getCueLightBinding: workspaceRepository.getCueLightBinding,
  getRepos: workspaceRepository.getRepos,
  getWorkspaceStartupPreset: workspaceRepository.getWorkspaceStartupPreset,
  hasWorkspaceGitSelection: workspaceRepository.hasWorkspaceGitSelection,
  listArchivedWorkspaces: workspaceRepository.listArchivedWorkspaces,
  listWorkspaces: workspaceRepository.listWorkspaces,
  normalizeWorkspaceStartupPreset: workspaceRepository.normalizeWorkspaceStartupPreset,
  normalizeWorkspaceStartupPresetRaw: workspaceRepository.normalizeWorkspaceStartupPresetRaw,
  openWorkspace: workspaceRepository.openWorkspace,
  readLastRepoByWorkspace,
  readLastWorkspaceId,
  rememberLastRepo,
  revealWorkspacePath: workspaceRepository.revealWorkspacePath,
  restoreWorkspace: workspaceRepository.restoreWorkspace,
  serializeWorkspaceStartupPreset: workspaceRepository.serializeWorkspaceStartupPreset,
  setRepoGitActive: workspaceRepository.setRepoGitActive,
  setRepoTrustLevel: workspaceRepository.setRepoTrustLevel,
  setWorkspaceStartupPreset: workspaceRepository.setWorkspaceStartupPreset,
  setWorkspaceStartupPresetRaw: workspaceRepository.setWorkspaceStartupPresetRaw,
  setWorkspaceGitActiveRepos: workspaceRepository.setWorkspaceGitActiveRepos,
  unbindCueLightProject: workspaceRepository.unbindCueLightProject,
  writeLastWorkspaceId,
};
